import './globals.css'
import { Noto_Sans_KR } from 'next/font/google'

const font = Noto_Sans_KR({
  subsets: ['latin'],
  weight:['400']
 })

export const metadata = {
  title: '효정/성민 소비물품 리스트',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
